### ISSUE TITLE
Error of the theme of classpip, var $color

### ISSUE THREAD

**Issue by teto82** [classpip/classpip-dashboard#31]
Hi, when i execute the dashboard, appear the next error:

![image](https://user-images.githubusercontent.com/12100506/31274736-8a8153b4-aa94-11e7-97e3-35da3ba849f6.png)

**Comment by ferranvila** [comment]
Fixed. Updated Framework UI to angular material and pinned dependencies into package-json

https://github.com/classpip/classpip-dashboard/pull/32
